services:
  quiver:
    image: ghcr.io/penaz89/quiver:2.0.0
    container_name: quiver
    ports:
      - "2222:2222"
    volumes:
      - quiver_data:/data
    restart: unless-stopped

volumes:
  quiver_data:
